[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
bip39 = "2.0"
sha2 = "0.10"
hmac = "0.12"
rand = "0.8"
hex = "0.4"
secp256k1 = { version = "0.29", features = ["rand", "serde"] }
ripemd = "0.1"
sha3 = "0.10"
